# GoReleaser configuration for terraform-provider-extip
# Visit https://goreleaser.com for documentation

before:
  hooks:
    - go mod tidy
    - go mod vendor

builds:
  - id: terraform-provider-extip
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      # Skip 32-bit darwin
      - goos: darwin
        goarch: '386'
      # Skip 32-bit arm on Windows (not common)
      - goos: windows
        goarch: arm
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  # Repo in which the release will be created.
  github:
    owner: petems
    name: terraform-provider-extip

  # If set to true, will not auto-publish the release.
  draft: false

  # Whether to remove existing draft releases
  replace_existing_draft: true

  # Useful if you want to delay the creation of the tag in the remote.
  disable: false

  # Set this to true if you want to disable just the artifact upload to the release.
  skip_upload: false

  # You can change the name of the release.
  name_template: "{{.Tag}}"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^docs:'
      - Merge pull request
      - Merge remote-tracking branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other
      order: 999