dist: trusty
sudo: false
language: go
go:
- "1.x"
- master

script:
- make test
- make fmtcheck
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_deploy:
- make targets
